name: Build binary - arm

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: self-hosted-arm64
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'
      - uses: actions/cache@v4
        with:
          path: "/home/runner/.konan"
          key: ${{ runner.os }}-${{ hashFiles('**/build.gradle.kts') }}
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libcurl4-openssl-dev
      - name: Build with Gradle
        run: ./gradlew commonBinaries
      - name: Move and apply correct permissions to binary
        run: |
          cp build/bin/common/releaseExecutable/slack-notifier-cli.kexe ./slack-notifier-cli
          chmod +x ./slack-notifier-cli
    #   - name: Upload executable
    #     uses: actions/upload-artifact@v4
    #     with:
    #       name: slack-notifier-cli-arm
    #       path: slack-notifier-cli-arm